### ISSUE TITLE
How do i book the seats?

### ISSUE THREAD

**Issue by fauziasf** [seatsio/seatsio-android#7]
Let say i already have configure the SeatingChartView and SeatingChartConfig, then the seating chart is showing on the App, after i selected the seats, how do i book them so the seats wont be available to be selected again?

**Comment by bverbeken** [comment]
You'll need to call the [seats.io API](https://docs.seats.io/docs/api-book-objects) to do so. 
Note that you should book seats from your server, not from the client - android or other.

**Comment by fauziasf** [comment]
this is the URL i post with the event id parameter:
`https://api.seatsio.net/events/event-1/actions/book`

here's what i put in the body, seatingobject.id in the objects, and a random number in the orderId:
`{"objects":["VIP-VIP Row 1-1","VIP-VIP Row 1-2"],"orderId":"1604468425113"}`

but theres no response, am i doing it the right way?

**Comment by bverbeken** [comment]
That looks correct at first sight, if you're [authenticating](https://docs.seats.io/docs/api-authentication) properly. Either way, you should always get a response (or a timeout), so be sure to check the response code and body. 

This is not related to seatsio-android, please reach out to support@seats.io for further help.

**Comment by fauziasf** [comment]
{"status":401,"messages":["User not found"],"errors":[{"code":"USER_NOT_FOUND","message":"User not found"}],"warnings":[],"requestId":"ed18ff24-342c-4ff1-aa23-71b2dc858b8c"}
