### ISSUE TITLE
Proguard-rules

### ISSUE THREAD

**Issue by oliviaezebube** [seatsio/seatsio-android#82]
Callbacks return null SeatsIoObject. I tried to add proguard rules below as suggested in the android sample app but that didn't work. Only works when I add this broad rule `-keep class io.seats.** { *; }`

```
-keepclassmembers class io.seats.seatingChart.SeatingChartJavascriptInterface {
  public *;
}
-keepclassmembers class io.seats.SeatsioJavascriptInterface {
  public *;
}
```

**Comment by mroloux** [comment]
We just released a new version that includes consumer Proguard rules: https://github.com/seatsio/seatsio-android/releases/tag/v12.3.0

So you shouldn't need to do anything inside your own Proguard configuration - everything should work automatically. Could you test this and confirm it's working as expected?

**Comment by oliviaezebube** [comment]
> We just released a new version that includes consumer Proguard rules: https://github.com/seatsio/seatsio-android/releases/tag/v12.3.0
> 
> So you shouldn't need to do anything inside your own Proguard configuration - everything should work automatically. Could you test this and confirm it's working as expected?

Hi! I can confirm that it works on the new version without having to add a Proguard rule. Thanks!
